config/routes.rb
Rails.application.routes.draw do
  root              to: 'static_pages#home'
  get    'about',   to: 'static_pages#about'
  get    'company', to: 'static_pages#company'
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50  }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < Applicationcontroller
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the rails5-todo"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "user deleted"
    redirect_to users_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # before filter

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <ul>
    <li><%= link_to '運営会社', company_path %></li>
    <li><%= link_to 'Rails5 Todo について', about_path %></li>
  </ul>
  <p>Copyright © 2016 Syati.info</p>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="m-header" >
    <div class="m-header-title h1">
      <%= link_to 'Rails5 Todo', root_path %>
    </div>
    <%= react_component('Header', {
      isLoggedIn: logged_in?,
      user: current_user
    }, {
      class: 'm-header-nav',
      prerender: true
    })
    %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? (t 'service.title', title: yield(:title)) : (t 'service.site_name')  %></title>
    <meta name="keywords"           content="<%= yield(:meta_keywords).presence || (t 'service.keywords') %>" />
    <meta name="description"        content="<%= yield(:meta_description).presence || (t 'service.description') %>" />
    <meta name="robots"             content="noodp" />
    <meta name="viewport"           content="width=device-width,initial-scale=1.0" />
    <meta property="og:title"       content="<%= content_for?(:title) ? (t 'service.title', title: yield(:title)) : (t 'service.site_name')  %>" />
    <meta property="og:description" content="<%= yield(:meta_description).presence || (t 'service.description') %>" />
    <meta property="og:site_name"   content="<%= t 'service.site_name' %>" />
    <meta property="og:image"       content="" />
    <meta property="og:type"        content="website" />
    <meta property="og:url"         content="" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main id="main">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/roots/index.html.erb
<% provide :title, "ページ個別タイトル" %>
<% provide :meta_description, "ページ個別デスクリプション" %>

<div>
  main
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    The form contains <%= pluralize(@user.errors.count, "error") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, "about" %>
<% provide :meta_description, "about について" %>

<div>
  about ページ
</div>

app/views/static_pages/company.html.erb
<% provide :title, "company" %>
<% provide :meta_description, "company ぺーじ" %>

<div>
 company page
</div>

app/views/static_pages/home.html.erb
<% provide :title, "ページ個別タイトル" %>
<% provide :meta_description, "ページ個別デスクリプション" %>

<div class="container">
  <div class="row">
    <h1>Hello Rails5 Todo</h1>
  </div>
  <div class="row">
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, "Edit" %>
<% provide :meta_description, "Edit Dayo" %>

<div class="container">
  <h1>Edit</h1>
  <div class="row">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div>
        <%= f.submit "Save changes", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, "All users" %>
<% provide :meta_description, "All users " %>

<div class="container">
  
  <ul class="users">
    <%= render @users %>
  </ul>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide :title, "Sign up" %>
<% provide :meta_description, "Sign up" %>

<div class="container">
  <h1>Sign up</h1>
  <div class="row">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div>
        <%= f.submit "Create my account", class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, "user" %>
<% provide :meta_description, "ユーザーページ" %>

<div class="container">
  <%= @user.name %>
  <%= @user.email %>
</div>